// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class ApiHubPluginRetry: ApiHubPluginStub {
    let inner: any ApiHubPluginStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ApiHubPluginStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getPlugin(
      request: GetPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.getPlugin(request: r, options: o)
        })
    }

    public func enablePlugin(
      request: EnablePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnablePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.enablePlugin(request: r, options: o)
        })
    }

    public func disablePlugin(
      request: DisablePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DisablePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.disablePlugin(request: r, options: o)
        })
    }

    public func createPlugin(
      request: CreatePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.createPlugin(request: r, options: o)
        })
    }

    public func listPlugins(
      request: ListPluginsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListPluginsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPluginsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListPluginsResponse
          in
          return try await self.inner.listPlugins(request: r, options: o)
        })
    }

    public func deletePlugin(
      request: DeletePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePlugin(request: r, options: o)
        })
    }

    public func createPluginInstance(
      request: CreatePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPluginInstance(request: r, options: o)
        })
    }

    public func executePluginInstanceAction(
      request: ExecutePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExecutePluginInstanceActionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.executePluginInstanceAction(request: r, options: o)
        })
    }

    public func getPluginInstance(
      request: GetPluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.PluginInstance {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.PluginInstance
          in
          return try await self.inner.getPluginInstance(request: r, options: o)
        })
    }

    public func listPluginInstances(
      request: ListPluginInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListPluginInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPluginInstancesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListPluginInstancesResponse
          in
          return try await self.inner.listPluginInstances(request: r, options: o)
        })
    }

    public func enablePluginInstanceAction(
      request: EnablePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnablePluginInstanceActionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.enablePluginInstanceAction(request: r, options: o)
        })
    }

    public func disablePluginInstanceAction(
      request: DisablePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DisablePluginInstanceActionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.disablePluginInstanceAction(request: r, options: o)
        })
    }

    public func updatePluginInstance(
      request: UpdatePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.PluginInstance {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.PluginInstance
          in
          return try await self.inner.updatePluginInstance(request: r, options: o)
        })
    }

    public func deletePluginInstance(
      request: DeletePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePluginInstance(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
