// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ApiHubPluginLogging: ApiHubPluginStub {
    let inner: any ApiHubPluginStub
    let logger: Logger

    public init(_ inner: any ApiHubPluginStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-apihub-v1"
      logger[metadataKey: "gcp.client.service"] = "apihub"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ApiHubPlugin"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getPlugin(
      request: GetPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPlugin",
        action: {
          (r: GetPluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.getPlugin(request: r, options: o)
        })
    }

    public func enablePlugin(
      request: EnablePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        name: "enablePlugin",
        action: {
          (r: EnablePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.enablePlugin(request: r, options: o)
        })
    }

    public func disablePlugin(
      request: DisablePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        name: "disablePlugin",
        action: {
          (r: DisablePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.disablePlugin(request: r, options: o)
        })
    }

    public func createPlugin(
      request: CreatePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPlugin",
        action: {
          (r: CreatePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Plugin
          in
          return try await self.inner.createPlugin(request: r, options: o)
        })
    }

    public func listPlugins(
      request: ListPluginsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListPluginsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPlugins",
        action: {
          (r: ListPluginsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListPluginsResponse
          in
          return try await self.inner.listPlugins(request: r, options: o)
        })
    }

    public func deletePlugin(
      request: DeletePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePlugin",
        action: {
          (r: DeletePluginRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePlugin(request: r, options: o)
        })
    }

    public func createPluginInstance(
      request: CreatePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPluginInstance",
        action: {
          (r: CreatePluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPluginInstance(request: r, options: o)
        })
    }

    public func executePluginInstanceAction(
      request: ExecutePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "executePluginInstanceAction",
        action: {
          (r: ExecutePluginInstanceActionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.executePluginInstanceAction(request: r, options: o)
        })
    }

    public func getPluginInstance(
      request: GetPluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.PluginInstance {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPluginInstance",
        action: {
          (r: GetPluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.PluginInstance
          in
          return try await self.inner.getPluginInstance(request: r, options: o)
        })
    }

    public func listPluginInstances(
      request: ListPluginInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListPluginInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPluginInstances",
        action: {
          (r: ListPluginInstancesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListPluginInstancesResponse
          in
          return try await self.inner.listPluginInstances(request: r, options: o)
        })
    }

    public func enablePluginInstanceAction(
      request: EnablePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "enablePluginInstanceAction",
        action: {
          (r: EnablePluginInstanceActionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.enablePluginInstanceAction(request: r, options: o)
        })
    }

    public func disablePluginInstanceAction(
      request: DisablePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "disablePluginInstanceAction",
        action: {
          (r: DisablePluginInstanceActionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.disablePluginInstanceAction(request: r, options: o)
        })
    }

    public func updatePluginInstance(
      request: UpdatePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.PluginInstance {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePluginInstance",
        action: {
          (r: UpdatePluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.PluginInstance
          in
          return try await self.inner.updatePluginInstance(request: r, options: o)
        })
    }

    public func deletePluginInstance(
      request: DeletePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePluginInstance",
        action: {
          (r: DeletePluginInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePluginInstance(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
