// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

/// This service is used for managing curations for processing API data consumed
/// from collect layer.
///
/// @Snippet(path: "ApiHubCurateQuickstart")
public class ApiHubCurateClient: Clients.ApiHubCurateProtocol {
  let inner: any Clients.ApiHubCurateStub

  /// Creates a new `ApiHubCurateClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiHubCurateStub = try Clients.ApiHubCurateTransport(options)
    inner = Clients.ApiHubCurateRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiHubCurateLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create a curation resource in the API hub.
  /// Once a curation resource is created, plugin instances can start using it.
  ///
  /// @Snippet(path: "ApiHubCurate_CreateCuration")
  public func createCuration(
    request: CreateCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Curation {
    try await self.inner.createCuration(request: request, options: options)
  }

  /// Get curation resource details.
  ///
  /// @Snippet(path: "ApiHubCurate_GetCuration")
  public func getCuration(
    request: GetCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Curation {
    try await self.inner.getCuration(request: request, options: options)
  }

  /// List curation resources in the API hub.
  ///
  /// @Snippet(path: "ApiHubCurate_ListCurations")
  public func listCurations(
    request: ListCurationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListCurationsResponse {
    try await self.inner.listCurations(request: request, options: options)
  }

  /// List curation resources in the API hub.
  ///
  /// @Snippet(path: "ApiHubCurate_ListCurations")
  public func listCurations(
    byItem: ListCurationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Curation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListCurationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCurations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Update a curation resource in the API hub. The following fields in the
  /// [curation][google.cloud.apihub.v1.Curation] can be updated:
  ///
  /// * [display_name][google.cloud.apihub.v1.Curation.display_name]
  /// * [description][google.cloud.apihub.v1.Curation.description]
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateApiRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// [google.cloud.apihub.v1.Curation]: <doc:Curation>
  /// [google.cloud.apihub.v1.Curation.description]: <doc:Curation/description>
  /// [google.cloud.apihub.v1.Curation.display_name]: <doc:Curation/displayName>
  /// [google.cloud.apihub.v1.UpdateApiRequest.update_mask]: <doc:UpdateApiRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHubCurate_UpdateCuration")
  public func updateCuration(
    request: UpdateCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Curation {
    try await self.inner.updateCuration(request: request, options: options)
  }

  /// Delete a curation resource in the API hub. A curation can only be deleted
  /// if it's not being used by any plugin instance.
  ///
  /// @Snippet(path: "ApiHubCurate_DeleteCuration")
  public func deleteCuration(
    request: DeleteCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteCuration(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHubCurate_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHubCurate_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ApiHubCurate_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubCurate_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubCurate_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubCurate_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubCurate_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubCurate_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiHubCurateClient`.
  ///
  /// To mock `ApiHubCurateClient` change your functions to receive
  /// `some ApiHubCurateProtocol` or `any ApiHubCurateProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiHubCurateProtocol {
    /// See `ApiHubCurateClient.createCuration`.
    func createCuration(request: CreateCurationRequest) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.createCuration`.
    func createCuration(
      parent: Swift.String,
      curation: Curation?,
      curationId: Swift.String,
    ) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.getCuration`.
    func getCuration(request: GetCurationRequest) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.getCuration`.
    func getCuration(
      name: Swift.String,
    ) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.listCurations`.
    func listCurations(request: ListCurationsRequest) async throws
      -> GoogleCloudApiHubV1.ListCurationsResponse

    /// See `ApiHubCurateClient.listCurations`.
    func listCurations(
      byItem: ListCurationsRequest
    ) throws -> any AsyncSequence<Curation, Swift.Error>

    /// See `ApiHubCurateClient.listCurations`.
    func listCurations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Curation, Swift.Error>

    /// See `ApiHubCurateClient.updateCuration`.
    func updateCuration(request: UpdateCurationRequest) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.updateCuration`.
    func updateCuration(
      curation: Curation?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.deleteCuration`.
    func deleteCuration(request: DeleteCurationRequest) async throws

    /// See `ApiHubCurateClient.deleteCuration`.
    func deleteCuration(
      name: Swift.String,
    ) async throws

    /// See `ApiHubCurateClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ApiHubCurateClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ApiHubCurateClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ApiHubCurateClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ApiHubCurateClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ApiHubCurateClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ApiHubCurateClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `ApiHubCurateClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ApiHubCurateClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `ApiHubCurateClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ApiHubCurateClient.createCuration`.
    func createCuration(
      request: CreateCurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.getCuration`.
    func getCuration(
      request: GetCurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.listCurations`.
    func listCurations(
      request: ListCurationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListCurationsResponse

    /// See `ApiHubCurateClient.listCurations`.
    func listCurations(
      byItem: ListCurationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Curation, Swift.Error>

    /// See `ApiHubCurateClient.updateCuration`.
    func updateCuration(
      request: UpdateCurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Curation

    /// See `ApiHubCurateClient.deleteCuration`.
    func deleteCuration(
      request: DeleteCurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ApiHubCurateClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ApiHubCurateClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ApiHubCurateClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ApiHubCurateClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ApiHubCurateClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ApiHubCurateClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ApiHubCurateClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ApiHubCurateProtocol {
  public func createCuration(request: CreateCurationRequest) async throws
    -> GoogleCloudApiHubV1.Curation
  {
    try await self.createCuration(request: request, options: .init())
  }

  public func createCuration(
    request: CreateCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Curation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCuration(
    parent: Swift.String,
    curation: Curation?,
    curationId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Curation {
    let request = CreateCurationRequest().with {
      $0.parent = parent
      $0.curation = curation
      $0.curationId = curationId
    }
    return try await self.createCuration(request: request)
  }

  public func getCuration(request: GetCurationRequest) async throws -> GoogleCloudApiHubV1.Curation
  {
    try await self.getCuration(request: request, options: .init())
  }

  public func getCuration(
    request: GetCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Curation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCuration(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Curation {
    let request = GetCurationRequest().with {
      $0.name = name
    }
    return try await self.getCuration(request: request)
  }

  public func listCurations(request: ListCurationsRequest) async throws
    -> GoogleCloudApiHubV1.ListCurationsResponse
  {
    try await self.listCurations(request: request, options: .init())
  }

  public func listCurations(
    request: ListCurationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListCurationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCurations(
    byItem: ListCurationsRequest
  ) throws -> any AsyncSequence<Curation, Swift.Error> {
    try self.listCurations(byItem: byItem, options: .init())
  }

  public func listCurations(
    byItem: ListCurationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Curation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListCurationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCurations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Curation, Swift.Error> {
    let request = ListCurationsRequest().with {
      $0.parent = parent
    }
    return try self.listCurations(byItem: request)
  }

  public func updateCuration(request: UpdateCurationRequest) async throws
    -> GoogleCloudApiHubV1.Curation
  {
    try await self.updateCuration(request: request, options: .init())
  }

  public func updateCuration(
    request: UpdateCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Curation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCuration(
    curation: Curation?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Curation {
    let request = UpdateCurationRequest().with {
      $0.curation = curation
      $0.updateMask = updateMask
    }
    return try await self.updateCuration(request: request)
  }

  public func deleteCuration(request: DeleteCurationRequest) async throws {
    try await self.deleteCuration(request: request, options: .init())
  }

  public func deleteCuration(
    request: DeleteCurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCuration(
    name: Swift.String,
  ) async throws {
    let request = DeleteCurationRequest().with {
      $0.name = name
    }
    try await self.deleteCuration(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
