// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ApiHubPluginStub: Sendable {
    func getPlugin(
      request: GetPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin

    func enablePlugin(
      request: EnablePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin

    func disablePlugin(
      request: DisablePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin

    func createPlugin(
      request: CreatePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Plugin

    func listPlugins(
      request: ListPluginsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListPluginsResponse

    func deletePlugin(
      request: DeletePluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createPluginInstance(
      request: CreatePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func executePluginInstanceAction(
      request: ExecutePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPluginInstance(
      request: GetPluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.PluginInstance

    func listPluginInstances(
      request: ListPluginInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListPluginInstancesResponse

    func enablePluginInstanceAction(
      request: EnablePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func disablePluginInstanceAction(
      request: DisablePluginInstanceActionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePluginInstance(
      request: UpdatePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.PluginInstance

    func deletePluginInstance(
      request: DeletePluginInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
