// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ApiHubDiscoveryStub: Sendable {
    func listDiscoveredApiObservations(
      request: ListDiscoveredApiObservationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse

    func getDiscoveredApiObservation(
      request: GetDiscoveredApiObservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.DiscoveredApiObservation

    func listDiscoveredApiOperations(
      request: ListDiscoveredApiOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse

    func getDiscoveredApiOperation(
      request: GetDiscoveredApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.DiscoveredApiOperation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
