// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The API metadata.
public struct APIMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The API resource to be pushed to Hub's collect layer. The ID of
  /// the API resource will be generated by Hub to ensure uniqueness across all
  /// APIs across systems.
  public var api: Api? = nil

  /// Optional. The list of versions present in an API resource.
  public var versions: [VersionMetadata] = []

  /// Optional. The unique identifier of the API in the system where it was
  /// originally created.
  public var originalId: Swift.String = Swift.String()

  /// Optional. Timestamp indicating when the API was created at the source.
  public var originalCreateTime: GoogleCloudWKT.Timestamp? = nil

  /// Required. Timestamp indicating when the API was last updated at the source.
  public var originalUpdateTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `APIMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = APIMetadata().with { $0.api = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.APIMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
