// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ConfigVariableTemplate represents a configuration variable template present
/// in a Plugin Config.
public struct ConfigVariableTemplate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. ID of the config variable. Must be unique within the
  /// configuration.
  public var id: Swift.String = Swift.String()

  /// Required. Type of the parameter: string, int, bool etc.
  public var valueType: ConfigVariableTemplate.ValueType = ConfigVariableTemplate.ValueType()

  /// Optional. Description.
  public var description: Swift.String = Swift.String()

  /// Optional. Regular expression in RE2 syntax used for validating the `value`
  /// of a `ConfigVariable`.
  public var validationRegex: Swift.String = Swift.String()

  /// Optional. Flag represents that this `ConfigVariable` must be provided for a
  /// PluginInstance.
  public var `required`: Swift.Bool = Swift.Bool()

  /// Optional. Enum options. To be populated if `ValueType` is `ENUM`.
  public var enumOptions: [ConfigValueOption] = []

  /// Optional. Multi select options. To be populated if `ValueType` is
  /// `MULTI_SELECT`.
  public var multiSelectOptions: [ConfigValueOption] = []

  /// Initialize a new instance of `ConfigVariableTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigVariableTemplate().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case id = "id"
    case valueType = "valueType"
    case description = "description"
    case validationRegex = "validationRegex"
    case `required` = "required"
    case enumOptions = "enumOptions"
    case multiSelectOptions = "multiSelectOptions"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.valueType = try container.decode(ConfigVariableTemplate.ValueType.self, forKey: .valueType)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.validationRegex = try container.decode(Swift.String.self, forKey: .validationRegex)
    self.`required` = try container.decode(Swift.Bool.self, forKey: .`required`)
    self.enumOptions = try container.decode([ConfigValueOption].self, forKey: .enumOptions)
    self.multiSelectOptions = try container.decode(
      [ConfigValueOption].self, forKey: .multiSelectOptions)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.valueType, forKey: .valueType)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.validationRegex, forKey: .validationRegex)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encode(self.enumOptions, forKey: .enumOptions)
    try container.encode(self.multiSelectOptions, forKey: .multiSelectOptions)
  }

  /// ValueType indicates the data type of the value.
  public enum ValueType: Codable, Equatable, Sendable {
    /// Value type is not specified.
    case unspecified
    /// Value type is string.
    case string
    /// Value type is integer.
    case int
    /// Value type is boolean.
    case bool
    /// Value type is secret.
    case secret
    /// Value type is enum.
    case `enum`
    /// Value type is multi select.
    case multiSelect
    /// Value type is multi string.
    case multiString
    /// Value type is multi int.
    case multiInt
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .int: return 2
      case .bool: return 3
      case .secret: return 4
      case .`enum`: return 5
      case .multiSelect: return 6
      case .multiString: return 7
      case .multiInt: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VALUE_TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .int: return "INT"
      case .bool: return "BOOL"
      case .secret: return "SECRET"
      case .`enum`: return "ENUM"
      case .multiSelect: return "MULTI_SELECT"
      case .multiString: return "MULTI_STRING"
      case .multiInt: return "MULTI_INT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ValueType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VALUE_TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INT": self = .int
      case "BOOL": self = .bool
      case "SECRET": self = .secret
      case "ENUM": self = .`enum`
      case "MULTI_SELECT": self = .multiSelect
      case "MULTI_STRING": self = .multiString
      case "MULTI_INT": self = .multiInt
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ValueType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .int
      case 3: self = .bool
      case 4: self = .secret
      case 5: self = .`enum`
      case 6: self = .multiSelect
      case 7: self = .multiString
      case 8: self = .multiInt
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .string: return try container.encode(1)
      case .int: return try container.encode(2)
      case .bool: return try container.encode(3)
      case .secret: return try container.encode(4)
      case .`enum`: return try container.encode(5)
      case .multiSelect: return try container.encode(6)
      case .multiString: return try container.encode(7)
      case .multiInt: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.ConfigVariableTemplate"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
