// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The [CreateApiOperation][google.cloud.apihub.v1.ApiHub.CreateApiOperation]
/// method's request.
///
/// [google.cloud.apihub.v1.ApiHub.CreateApiOperation]: <doc:ApiHubClient/createApiOperation(request:options:)>
public struct CreateApiOperationRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent resource for the operation resource.
  /// Format:
  /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The ID to use for the operation resource, which will become the
  /// final component of the operation's resource name. This field is optional.
  ///
  /// * If provided, the same will be used. The service will throw an error if
  /// the specified id is already used by another operation resource in the API
  /// hub.
  /// * If not provided, a system generated id will be used.
  ///
  /// This value should be 4-500 characters, overall resource name which
  /// will be of format
  /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}/operations/{operation}`,
  /// its length is limited to 700 characters, and valid characters are
  /// /[a-z][A-Z][0-9]-_/.
  public var apiOperationId: Swift.String = Swift.String()

  /// Required. The operation resource to create.
  public var apiOperation: ApiOperation? = nil

  /// Initialize a new instance of `CreateApiOperationRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateApiOperationRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.CreateApiOperationRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
