// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The curation information for this plugin instance.
public struct CurationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The curation type for this plugin instance.
  public var curationType: CurationType = CurationType()

  /// The curation information for this plugin instance.
  public var curationConfig: OneOf_CurationConfig? = nil

  /// Initialize a new instance of `CurationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CurationConfig().with { $0.customCuration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case customCuration = "customCuration"
    case curationType = "curationType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.curationType = try container.decode(CurationType.self, forKey: .curationType)

    var curationConfig: OneOf_CurationConfig? = nil
    let curationConfigCheckAndSet = {
      if curationConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'curationConfig'"))
      }
      curationConfig = $0
    }
    if let customCuration = try container.decodeIfPresent(
      CurationConfig.CustomCuration?.self, forKey: .customCuration)
    {
      try curationConfigCheckAndSet(.customCuration(customCuration))
    }
    self.curationConfig = curationConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.curationType, forKey: .curationType)

    if let choice = self.curationConfig {
      switch choice {
      case .customCuration(let value):
        try container.encode(value, forKey: .customCuration)
      }
    }
  }

  /// Custom curation information for this plugin instance.
  public struct CustomCuration: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The unique name of the curation resource. This will be the name
    /// of the curation resource in the format:
    /// `projects/{project}/locations/{location}/curations/{curation}`
    public var curation: Swift.String = Swift.String()

    /// Initialize a new instance of `CustomCuration`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomCuration().with { $0.curation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.CurationConfig.CustomCuration"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The curation information for this plugin instance.
  public enum OneOf_CurationConfig: Codable, Equatable, Sendable {
    /// Optional. Custom curation information for this plugin instance.
    indirect case customCuration(CurationConfig.CustomCuration?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.CurationConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
