// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of the deployment where APIs are hosted.
/// A deployment could represent an Apigee proxy, API gateway, other Google Cloud
/// services or non-Google Cloud services as well. A deployment entity is a root
/// level entity in the API hub and exists independent of any API.
public struct Deployment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the deployment.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/deployments/{deployment}`
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the deployment.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the deployment.
  public var description: Swift.String = Swift.String()

  /// Optional. The documentation of the deployment.
  public var documentation: Documentation? = nil

  /// Required. The type of deployment.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-deployment-type`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var deploymentType: AttributeValues? = nil

  /// Required. The resource URI identifies the deployment within its gateway.
  /// For Apigee gateways, its recommended to use the format:
  /// organizations/{org}/environments/{env}/apis/{api}.
  /// For ex: if a proxy with name `orders` is deployed in `staging`
  /// environment of `cymbal` organization, the resource URI would be:
  /// `organizations/cymbal/environments/staging/apis/orders`.
  public var resourceUri: Swift.String = Swift.String()

  /// Required. The endpoints at which this deployment resource is listening for
  /// API requests. This could be a list of complete URIs, hostnames or an IP
  /// addresses.
  public var endpoints: [Swift.String] = []

  /// Output only. The API versions linked to this deployment.
  /// Note: A particular deployment could be linked to multiple different API
  /// versions (of same or different APIs).
  public var apiVersions: [Swift.String] = []

  /// Output only. The time at which the deployment was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time at which the deployment was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. The SLO for this deployment.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-slo`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var slo: AttributeValues? = nil

  /// Optional. The environment mapping to this deployment.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-environment`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var environment: AttributeValues? = nil

  /// Optional. The list of user defined attributes associated with the
  /// deployment resource. The key is the attribute name. It will be of the
  /// format: `projects/{project}/locations/{location}/attributes/{attribute}`.
  /// The value is the attribute values associated with the resource.
  public var attributes: [Swift.String: AttributeValues] = [:]

  /// Output only. The list of sources and metadata from the sources of the
  /// deployment.
  public var sourceMetadata: [SourceMetadata] = []

  /// Optional. The uri where users can navigate to for the management of the
  /// deployment. This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-management-url`
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. The value of the attribute should be a valid URL.
  public var managementUrl: AttributeValues? = nil

  /// Optional. The uri where additional source specific information for this
  /// deployment can be found. This maps to the following system defined
  /// attribute:
  /// `projects/{project}/locations/{location}/attributes/system-source-uri`
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. The value of the attribute should be a valid URI, and in case
  /// of Cloud Storage URI, it should point to a Cloud Storage object,
  /// not a directory.
  public var sourceUri: AttributeValues? = nil

  /// Optional. The project to which the deployment belongs.
  /// For GCP gateways, this will refer to the project identifier.
  /// For others like Edge/OPDK, this will refer to the org identifier.
  public var sourceProject: Swift.String = Swift.String()

  /// Optional. The environment at source for the deployment.
  /// For example: prod, dev, staging, etc.
  public var sourceEnvironment: Swift.String = Swift.String()

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Deployment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
