// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The endpoint to be triggered for curation.
/// The endpoint will be invoked with a request payload containing
/// [ApiMetadata][google.cloud.apihub.v1.ApiHub.ApiMetadata].
/// Response should contain curated data in the form of
/// [ApiMetadata][google.cloud.apihub.v1.ApiHub.ApiMetadata].
public struct Endpoint: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The details of the endpoint to be triggered for curation.
  public var endpointDetails: OneOf_EndpointDetails? = nil

  /// Initialize a new instance of `Endpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Endpoint().with { $0.applicationIntegrationEndpointDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case applicationIntegrationEndpointDetails = "applicationIntegrationEndpointDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var endpointDetails: OneOf_EndpointDetails? = nil
    let endpointDetailsCheckAndSet = {
      if endpointDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'endpointDetails'"))
      }
      endpointDetails = $0
    }
    if let applicationIntegrationEndpointDetails = try container.decodeIfPresent(
      ApplicationIntegrationEndpointDetails?.self, forKey: .applicationIntegrationEndpointDetails)
    {
      try endpointDetailsCheckAndSet(
        .applicationIntegrationEndpointDetails(applicationIntegrationEndpointDetails))
    }
    self.endpointDetails = endpointDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.endpointDetails {
      switch choice {
      case .applicationIntegrationEndpointDetails(let value):
        try container.encode(value, forKey: .applicationIntegrationEndpointDetails)
      }
    }
  }

  /// The details of the endpoint to be triggered for curation.
  public enum OneOf_EndpointDetails: Codable, Equatable, Sendable {
    /// Required. The details of the Application Integration endpoint to be
    /// triggered for curation.
    indirect case applicationIntegrationEndpointDetails(ApplicationIntegrationEndpointDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Endpoint"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
