// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// This service is used for managing the host project registrations.
///
/// @Snippet(path: "HostProjectRegistrationServiceQuickstart")
public final class HostProjectRegistrationServiceClient: Clients
    .HostProjectRegistrationServiceProtocol, Sendable
{
  let inner: any Clients.HostProjectRegistrationServiceStub

  /// Creates a new `HostProjectRegistrationServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.HostProjectRegistrationServiceStub =
      try Clients.HostProjectRegistrationServiceTransport(options)
    inner = Clients.HostProjectRegistrationServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.HostProjectRegistrationServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create a host project registration.
  /// A Google cloud project can be registered as a host project if it is not
  /// attached as a runtime project to another host project.
  /// A project can be registered as a host project only once. Subsequent
  /// register calls for the same project will fail.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_CreateHostProjectRegistration")
  public func createHostProjectRegistration(
    request: CreateHostProjectRegistrationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration {
    try await self.inner.createHostProjectRegistration(request: request, options: options)
  }

  /// Get a host project registration.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_GetHostProjectRegistration")
  public func getHostProjectRegistration(
    request: GetHostProjectRegistrationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration {
    try await self.inner.getHostProjectRegistration(request: request, options: options)
  }

  /// Lists host project registrations.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_ListHostProjectRegistrations")
  public func listHostProjectRegistrations(
    request: ListHostProjectRegistrationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse {
    try await self.inner.listHostProjectRegistrations(request: request, options: options)
  }

  /// Lists host project registrations.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_ListHostProjectRegistrations")
  public func listHostProjectRegistrations(
    byItem: ListHostProjectRegistrationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listHostProjectRegistrations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "HostProjectRegistrationService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HostProjectRegistrationService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HostProjectRegistrationService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HostProjectRegistrationService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HostProjectRegistrationService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HostProjectRegistrationService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `HostProjectRegistrationServiceClient`.
  ///
  /// To mock `HostProjectRegistrationServiceClient` change your functions to receive
  /// `some HostProjectRegistrationServiceProtocol` or `any HostProjectRegistrationServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol HostProjectRegistrationServiceProtocol {
    /// See `HostProjectRegistrationServiceClient.createHostProjectRegistration`.
    func createHostProjectRegistration(request: CreateHostProjectRegistrationRequest) async throws
      -> GoogleCloudApiHubV1.HostProjectRegistration

    /// See `HostProjectRegistrationServiceClient.createHostProjectRegistration`.
    func createHostProjectRegistration(
      parent: Swift.String,
      hostProjectRegistration: HostProjectRegistration?,
      hostProjectRegistrationId: Swift.String,
    ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration

    /// See `HostProjectRegistrationServiceClient.getHostProjectRegistration`.
    func getHostProjectRegistration(request: GetHostProjectRegistrationRequest) async throws
      -> GoogleCloudApiHubV1.HostProjectRegistration

    /// See `HostProjectRegistrationServiceClient.getHostProjectRegistration`.
    func getHostProjectRegistration(
      name: Swift.String,
    ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration

    /// See `HostProjectRegistrationServiceClient.listHostProjectRegistrations`.
    func listHostProjectRegistrations(request: ListHostProjectRegistrationsRequest) async throws
      -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse

    /// See `HostProjectRegistrationServiceClient.listHostProjectRegistrations`.
    func listHostProjectRegistrations(
      byItem: ListHostProjectRegistrationsRequest
    ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.listHostProjectRegistrations`.
    func listHostProjectRegistrations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `HostProjectRegistrationServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `HostProjectRegistrationServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `HostProjectRegistrationServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `HostProjectRegistrationServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `HostProjectRegistrationServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `HostProjectRegistrationServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `HostProjectRegistrationServiceClient.createHostProjectRegistration`.
    func createHostProjectRegistration(
      request: CreateHostProjectRegistrationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration

    /// See `HostProjectRegistrationServiceClient.getHostProjectRegistration`.
    func getHostProjectRegistration(
      request: GetHostProjectRegistrationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration

    /// See `HostProjectRegistrationServiceClient.listHostProjectRegistrations`.
    func listHostProjectRegistrations(
      request: ListHostProjectRegistrationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse

    /// See `HostProjectRegistrationServiceClient.listHostProjectRegistrations`.
    func listHostProjectRegistrations(
      byItem: ListHostProjectRegistrationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `HostProjectRegistrationServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `HostProjectRegistrationServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `HostProjectRegistrationServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `HostProjectRegistrationServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `HostProjectRegistrationServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.HostProjectRegistrationServiceProtocol {
  public func createHostProjectRegistration(request: CreateHostProjectRegistrationRequest)
    async throws -> GoogleCloudApiHubV1.HostProjectRegistration
  {
    try await self.createHostProjectRegistration(request: request, options: .init())
  }

  public func createHostProjectRegistration(
    request: CreateHostProjectRegistrationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createHostProjectRegistration(
    parent: Swift.String,
    hostProjectRegistration: HostProjectRegistration?,
    hostProjectRegistrationId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration {
    let request = CreateHostProjectRegistrationRequest().with {
      $0.parent = parent
      $0.hostProjectRegistration = hostProjectRegistration
      $0.hostProjectRegistrationId = hostProjectRegistrationId
    }
    return try await self.createHostProjectRegistration(request: request)
  }

  public func getHostProjectRegistration(request: GetHostProjectRegistrationRequest) async throws
    -> GoogleCloudApiHubV1.HostProjectRegistration
  {
    try await self.getHostProjectRegistration(request: request, options: .init())
  }

  public func getHostProjectRegistration(
    request: GetHostProjectRegistrationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getHostProjectRegistration(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.HostProjectRegistration {
    let request = GetHostProjectRegistrationRequest().with {
      $0.name = name
    }
    return try await self.getHostProjectRegistration(request: request)
  }

  public func listHostProjectRegistrations(request: ListHostProjectRegistrationsRequest)
    async throws -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse
  {
    try await self.listHostProjectRegistrations(request: request, options: .init())
  }

  public func listHostProjectRegistrations(
    request: ListHostProjectRegistrationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listHostProjectRegistrations(
    byItem: ListHostProjectRegistrationsRequest
  ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error> {
    try self.listHostProjectRegistrations(byItem: byItem, options: .init())
  }

  public func listHostProjectRegistrations(
    byItem: ListHostProjectRegistrationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListHostProjectRegistrationsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listHostProjectRegistrations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<HostProjectRegistration, Swift.Error> {
    let request = ListHostProjectRegistrationsRequest().with {
      $0.parent = parent
    }
    return try self.listHostProjectRegistrations(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
