// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The HTTP Operation.
public struct HttpOperation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The path details for the Operation.
  /// Note: Even though this field is optional, it is required for
  /// [CreateApiOperation][google.cloud.apihub.v1.ApiHub.CreateApiOperation]
  /// API and we will fail the request if not provided.
  ///
  /// [google.cloud.apihub.v1.ApiHub.CreateApiOperation]: <doc:ApiHub/createApiOperation(request:)>
  public var path: Path? = nil

  /// Optional. Operation method
  /// Note: Even though this field is optional, it is required for
  /// [CreateApiOperation][google.cloud.apihub.v1.ApiHub.CreateApiOperation]
  /// API and we will fail the request if not provided.
  ///
  /// [google.cloud.apihub.v1.ApiHub.CreateApiOperation]: <doc:ApiHub/createApiOperation(request:)>
  public var method: HttpOperation.Method = HttpOperation.Method()

  /// Initialize a new instance of `HttpOperation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpOperation().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enumeration of Method types.
  public enum Method: Codable, Equatable, Sendable {
    /// Method unspecified.
    case unspecified
    /// Get Operation type.
    case `get`
    /// Put Operation type.
    case put
    /// Post Operation type.
    case post
    /// Delete Operation type.
    case delete
    /// Options Operation type.
    case options
    /// Head Operation type.
    case head
    /// Patch Operation type.
    case patch
    /// Trace Operation type.
    case trace
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`get`: return 1
      case .put: return 2
      case .post: return 3
      case .delete: return 4
      case .options: return 5
      case .head: return 6
      case .patch: return 7
      case .trace: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METHOD_UNSPECIFIED"
      case .`get`: return "GET"
      case .put: return "PUT"
      case .post: return "POST"
      case .delete: return "DELETE"
      case .options: return "OPTIONS"
      case .head: return "HEAD"
      case .patch: return "PATCH"
      case .trace: return "TRACE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METHOD_UNSPECIFIED": self = .unspecified
      case "GET": self = .`get`
      case "PUT": self = .put
      case "POST": self = .post
      case "DELETE": self = .delete
      case "OPTIONS": self = .options
      case "HEAD": self = .head
      case "PATCH": self = .patch
      case "TRACE": self = .trace
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`get`
      case 2: self = .put
      case 3: self = .post
      case 4: self = .delete
      case 5: self = .options
      case 6: self = .head
      case 7: self = .patch
      case 8: self = .trace
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`get`: return try container.encode(1)
      case .put: return try container.encode(2)
      case .post: return try container.encode(3)
      case .delete: return try container.encode(4)
      case .options: return try container.encode(5)
      case .head: return try container.encode(6)
      case .patch: return try container.encode(7)
      case .trace: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.HttpOperation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
