// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Issue contains the details of a single issue found by the linter.
public struct Issue: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Rule code unique to each rule defined in linter.
  public var code: Swift.String = Swift.String()

  /// Required. An array of strings indicating the location in the analyzed
  /// document where the rule was triggered.
  public var path: [Swift.String] = []

  /// Required. Human-readable message describing the issue found by the linter.
  public var message: Swift.String = Swift.String()

  /// Required. Severity level of the rule violation.
  public var severity: Severity = Severity()

  /// Required. Object describing where in the file the issue was found.
  public var range: Range? = nil

  /// Initialize a new instance of `Issue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Issue().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Issue"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
