// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The [ListPlugins][google.cloud.apihub.v1.ApiHubPlugin.ListPlugins] method's
/// request.
///
/// [google.cloud.apihub.v1.ApiHubPlugin.ListPlugins]: <doc:ApiHubPlugin/listPlugins(request:)>
public struct ListPluginsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this plugin will be created.
  /// Format: `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. An expression that filters the list of plugins.
  ///
  /// A filter expression consists of a field name, a comparison
  /// operator, and a value for filtering. The value must be a string. The
  /// comparison operator must be one of: `<`, `>` or
  /// `=`. Filters are not case sensitive.
  ///
  /// The following fields in the `Plugins` are eligible for filtering:
  ///
  ///   * `plugin_category` - The category of the Plugin. Allowed
  ///   comparison operators: `=`.
  ///
  /// Expressions are combined with either `AND` logic operator or `OR` logical
  /// operator but not both of them together i.e. only one of the `AND` or `OR`
  /// operator can be used throughout the filter string and both the operators
  /// cannot be used together. No other logical operators are
  /// supported. At most three filter fields are allowed in the filter
  /// string and if provided more than that then `INVALID_ARGUMENT` error is
  /// returned by the API.
  /// Here are a few examples:
  ///
  ///   * `plugin_category = ON_RAMP` - The plugin is of category
  ///   on ramp.
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of hub plugins to return. The service may
  /// return fewer than this value. If unspecified, at most 50 hub plugins will
  /// be returned. The maximum value is 1000; values above 1000 will be coerced
  /// to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous `ListPlugins` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters (except page_size) provided to
  /// `ListPlugins` must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListPluginsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPluginsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.ListPluginsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
