// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The
/// [ListDependencies][google.cloud.apihub.v1.ApiHubDependencies.ListDependencies]
/// method's request.
///
/// [google.cloud.apihub.v1.ApiHubDependencies.ListDependencies]: <doc:ApiHubDependenciesClient/listDependencies(request:options:)>
public struct ListDependenciesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent which owns this collection of dependency resources.
  /// Format: `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. An expression that filters the list of Dependencies.
  ///
  /// A filter expression consists of a field name, a comparison operator, and
  /// a value for filtering. The value must be a string. Allowed comparison
  /// operator is `=`. Filters are not case sensitive.
  ///
  /// The following fields in the `Dependency` are eligible for filtering:
  ///
  ///   * `consumer.operation_resource_name` - The operation resource name for
  ///   the consumer entity involved in a dependency. Allowed comparison
  ///   operators: `=`.
  ///   * `consumer.external_api_resource_name` - The external api resource name
  ///   for the consumer entity involved in a dependency. Allowed comparison
  ///   operators: `=`.
  ///   * `supplier.operation_resource_name` - The operation resource name for
  ///   the supplier entity involved in a dependency. Allowed comparison
  ///   operators: `=`.
  ///   * `supplier.external_api_resource_name` - The external api resource name
  ///   for the supplier entity involved in a dependency. Allowed comparison
  ///   operators: `=`.
  ///
  /// Expressions are combined with either `AND` logic operator or `OR` logical
  /// operator but not both of them together i.e. only one of the `AND` or `OR`
  /// operator can be used throughout the filter string and both the operators
  /// cannot be used together. No other logical operators are supported. At most
  /// three filter fields are allowed in the filter string and if provided
  /// more than that then `INVALID_ARGUMENT` error is returned by the API.
  ///
  /// For example, `consumer.operation_resource_name =
  /// \"projects/p1/locations/global/apis/a1/versions/v1/operations/o1\" OR
  /// supplier.operation_resource_name =
  /// \"projects/p1/locations/global/apis/a1/versions/v1/operations/o1\"` - The
  /// dependencies with either consumer or supplier operation resource name as
  /// _projects/p1/locations/global/apis/a1/versions/v1/operations/o1_.
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of dependency resources to return. The service
  /// may return fewer than this value. If unspecified, at most 50 dependencies
  /// will be returned. The maximum value is 1000; values above 1000 will be
  /// coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous `ListDependencies` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to `ListDependencies` must
  /// match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListDependenciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDependenciesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.ListDependenciesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
