// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The [ListCurations][ApiHub.ListCurations] method's request.
public struct ListCurationsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of curation resources.
  /// Format: `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. An expression that filters the list of curation resources.
  ///
  /// A filter expression consists of a field name, a comparison
  /// operator, and a value for filtering. The value must be a string. The
  /// comparison operator must be one of: `<`, `>`, `:` or `=`. Filters are case
  /// insensitive.
  ///
  /// The following fields in the `curation resource` are eligible for filtering:
  ///
  ///   * `create_time` - The time at which the curation was created.
  ///   The value should be in the (RFC3339)[https://tools.ietf.org/html/rfc3339]
  ///   format. Allowed comparison operators: `>` and `<`.
  ///   * `display_name` - The display name of the curation. Allowed
  ///   comparison operators: `=`.
  ///   * `state` - The state of the curation. Allowed comparison operators: `=`.
  ///
  /// Expressions are combined with either `AND` logic operator or `OR` logical
  /// operator but not both of them together i.e. only one of the `AND` or `OR`
  /// operator can be used throughout the filter string and both the operators
  /// cannot be used together. No other logical operators are supported. At most
  /// three filter fields are allowed in the filter string and if provided
  /// more than that then `INVALID_ARGUMENT` error is returned by the API.
  ///
  /// Here are a few examples:
  ///
  ///   * `create_time < \"2021-08-15T14:50:00Z\" AND create_time >
  ///   \"2021-08-10T12:00:00Z\"` -
  ///   The curation resource was created before _2021-08-15 14:50:00 UTC_ and
  ///   after _2021-08-10 12:00:00 UTC_.
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of curation resources to return. The service
  /// may return fewer than this value. If unspecified, at most 50 curations will
  /// be returned. The maximum value is 1000; values above 1000 will be coerced
  /// to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous `ListCurations` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters (except page_size) provided to
  /// `ListCurations` must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCurationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCurationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.ListCurationsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
