// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// PluginInstanceAction represents an action which can be executed in the plugin
/// instance.
public struct PluginInstanceAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. This should map to one of the [action
  /// id][google.cloud.apihub.v1.PluginActionConfig.id] specified in
  /// [actions_config][google.cloud.apihub.v1.Plugin.actions_config] in the
  /// plugin.
  ///
  /// [google.cloud.apihub.v1.Plugin.actions_config]: <doc:Plugin/actionsConfig>
  /// [google.cloud.apihub.v1.PluginActionConfig.id]: <doc:PluginActionConfig/id>
  public var actionId: Swift.String = Swift.String()

  /// Output only. The current state of the plugin action in the plugin instance.
  public var state: PluginInstanceAction.State = PluginInstanceAction.State()

  /// Optional. The schedule for this plugin instance action. This can only be
  /// set if the plugin supports API_HUB_SCHEDULE_TRIGGER mode for this action.
  public var scheduleCronExpression: Swift.String = Swift.String()

  /// Optional. This configuration should be provided if the plugin action is
  /// publishing data to API hub curate layer.
  public var curationConfig: CurationConfig? = nil

  /// Optional. The time zone for the schedule cron expression. If not provided,
  /// UTC will be used.
  public var scheduleTimeZone: Swift.String = Swift.String()

  /// Optional. The service account used to publish data. Note, the service
  /// account will only be accepted for non GCP plugins like OPDK.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. The configuration of resources created for a given plugin
  /// instance action. Note these will be returned only in case of Non-GCP
  /// plugins like OPDK.
  public var resourceConfig: PluginInstanceAction.ResourceConfig? = nil

  /// The status of the plugin action.
  public var actionStatus: OneOf_ActionStatus? = nil

  /// Initialize a new instance of `PluginInstanceAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PluginInstanceAction().with { $0.hubInstanceAction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case hubInstanceAction = "hubInstanceAction"
    case actionId = "actionId"
    case state = "state"
    case scheduleCronExpression = "scheduleCronExpression"
    case curationConfig = "curationConfig"
    case scheduleTimeZone = "scheduleTimeZone"
    case serviceAccount = "serviceAccount"
    case resourceConfig = "resourceConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.actionId = try container.decode(Swift.String.self, forKey: .actionId)
    self.state = try container.decode(PluginInstanceAction.State.self, forKey: .state)
    self.scheduleCronExpression = try container.decode(
      Swift.String.self, forKey: .scheduleCronExpression)
    self.curationConfig = try container.decodeIfPresent(
      CurationConfig.self, forKey: .curationConfig)
    self.scheduleTimeZone = try container.decode(Swift.String.self, forKey: .scheduleTimeZone)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.resourceConfig = try container.decodeIfPresent(
      PluginInstanceAction.ResourceConfig.self, forKey: .resourceConfig)

    var actionStatus: OneOf_ActionStatus? = nil
    let actionStatusCheckAndSet = {
      if actionStatus != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'actionStatus'"))
      }
      actionStatus = $0
    }
    if let hubInstanceAction = try container.decodeIfPresent(
      ExecutionStatus?.self, forKey: .hubInstanceAction)
    {
      try actionStatusCheckAndSet(.hubInstanceAction(hubInstanceAction))
    }
    self.actionStatus = actionStatus
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.actionId, forKey: .actionId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.scheduleCronExpression, forKey: .scheduleCronExpression)
    try container.encode(self.curationConfig, forKey: .curationConfig)
    try container.encode(self.scheduleTimeZone, forKey: .scheduleTimeZone)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.resourceConfig, forKey: .resourceConfig)

    if let choice = self.actionStatus {
      switch choice {
      case .hubInstanceAction(let value):
        try container.encode(value, forKey: .hubInstanceAction)
      }
    }
  }

  /// The configuration of resources created for a given plugin instance action.
  public struct ResourceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The type of the action.
    public var actionType: ActionType = ActionType()

    /// Output only. The pubsub topic to publish the data to. Format is
    /// projects/{project}/topics/{topic}
    public var pubsubTopic: Swift.String = Swift.String()

    /// Initialize a new instance of `ResourceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceConfig().with { $0.actionType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.PluginInstanceAction.ResourceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// State represents the state of the plugin instance action.
  public enum State: Codable, Equatable, Sendable {
    /// Default unspecified state.
    case unspecified
    /// The action is enabled in the plugin instance i.e., executions can
    /// be triggered for this action.
    case enabled
    /// The action is disabled in the plugin instance i.e., no executions
    /// can be triggered for this action. This state indicates that the user
    /// explicitly disabled the instance, and no further action is needed unless
    /// the user wants to re-enable it.
    case disabled
    /// The action in the plugin instance is being enabled.
    case enabling
    /// The action in the plugin instance is being disabled.
    case disabling
    /// The ERROR state can come while enabling/disabling plugin instance action.
    /// Users can retrigger enable, disable via
    /// [EnablePluginInstanceAction][google.cloud.apihub.v1.ApiHubPlugin.EnablePluginInstanceAction]
    /// and
    /// [DisablePluginInstanceAction][google.cloud.apihub.v1.ApiHubPlugin.DisablePluginInstanceAction]
    /// to restore the action back to enabled/disabled state. Note enable/disable
    /// on actions can only be triggered if plugin instance is in Active state.
    ///
    /// [google.cloud.apihub.v1.ApiHubPlugin.DisablePluginInstanceAction]: <doc:ApiHubPluginClient/disablePluginInstanceAction(request:options:)>
    /// [google.cloud.apihub.v1.ApiHubPlugin.EnablePluginInstanceAction]: <doc:ApiHubPluginClient/enablePluginInstanceAction(request:options:)>
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .enabling: return 3
      case .disabling: return 4
      case .error: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .enabling: return "ENABLING"
      case .disabling: return "DISABLING"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "ENABLING": self = .enabling
      case "DISABLING": self = .disabling
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .enabling
      case 4: self = .disabling
      case 5: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabled: return try container.encode(1)
      case .disabled: return try container.encode(2)
      case .enabling: return try container.encode(3)
      case .disabling: return try container.encode(4)
      case .error: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The status of the plugin action.
  public enum OneOf_ActionStatus: Codable, Equatable, Sendable {
    /// Optional. The execution information for the plugin instance action done
    /// corresponding to an API hub instance.
    indirect case hubInstanceAction(ExecutionStatus?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.PluginInstanceAction"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
