// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The [SearchResources][google.cloud.apihub.v1.ApiHub.SearchResources] method's
/// request.
///
/// [google.cloud.apihub.v1.ApiHub.SearchResources]: <doc:ApiHubClient/searchResources(request:options:)>
public struct SearchResourcesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the location which will be of the type
  /// `projects/{project_id}/locations/{location_id}`. This field is used to
  /// identify the instance of API-Hub in which resources should be searched.
  public var location: Swift.String = Swift.String()

  /// Required. The free text search query. This query can contain keywords which
  /// could be related to any detail of the API-Hub resources such display names,
  /// descriptions, attributes etc.
  public var query: Swift.String = Swift.String()

  /// Optional. An expression that filters the list of search results.
  ///
  /// A filter expression consists of a field name, a comparison operator,
  /// and a value for filtering. The value must be a string, a number, or a
  /// boolean. The comparison operator must be `=`. Filters are not case
  /// sensitive.
  ///
  /// The following field names are eligible for filtering:
  ///    * `resource_type` - The type of resource in the search results.
  ///    Must be one of the following: `Api`, `ApiOperation`, `Deployment`,
  ///    `Definition`, `Spec` or `Version`. This field can only be specified once
  ///    in the filter.
  ///
  /// Here are is an example:
  ///
  ///   * `resource_type = Api` - The resource_type is _Api_.
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of search results to return. The service may
  /// return fewer than this value. If unspecified at most 10 search results will
  /// be returned. If value is negative then `INVALID_ARGUMENT` error is
  /// returned. The maximum value is 25; values above 25 will be coerced to 25.
  /// While paginating, you can specify a new page size parameter for each page
  /// of search results to be listed.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous
  /// [SearchResources][SearchResources]
  /// call. Specify this parameter to retrieve the next page of transactions.
  ///
  /// When paginating, you must specify the `page_token` parameter and all the
  /// other parameters except
  /// [page_size][google.cloud.apihub.v1.SearchResourcesRequest.page_size]
  /// should be specified with the same value which was used in the previous
  /// call. If the other fields are set with a different value than the previous
  /// call then `INVALID_ARGUMENT` error is returned.
  ///
  /// [google.cloud.apihub.v1.SearchResourcesRequest.page_size]: <doc:SearchResourcesRequest/pageSize>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `SearchResourcesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchResourcesRequest().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.SearchResourcesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
