// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// SpecDetails contains the details parsed from supported
/// spec types.
public struct SpecDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The description of the spec.
  public var description: Swift.String = Swift.String()

  public var details: OneOf_Details? = nil

  /// Initialize a new instance of `SpecDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpecDetails().with { $0.openApiSpecDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case openApiSpecDetails = "openApiSpecDetails"
    case description = "description"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decode(Swift.String.self, forKey: .description)

    var details: OneOf_Details? = nil
    let detailsCheckAndSet = {
      if details != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'details'"))
      }
      details = $0
    }
    if let openApiSpecDetails = try container.decodeIfPresent(
      OpenApiSpecDetails?.self, forKey: .openApiSpecDetails)
    {
      try detailsCheckAndSet(.openApiSpecDetails(openApiSpecDetails))
    }
    self.details = details
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)

    if let choice = self.details {
      switch choice {
      case .openApiSpecDetails(let value):
        try container.encode(value, forKey: .openApiSpecDetails)
      }
    }
  }

  public enum OneOf_Details: Codable, Equatable, Sendable {
    /// Output only. Additional details apart from `OperationDetails` parsed from
    /// an OpenAPI spec. The OperationDetails parsed from the spec can be
    /// obtained by using
    /// [ListAPIOperations][google.cloud.apihub.v1.ApiHub.ListApiOperations]
    /// method.
    ///
    /// [google.cloud.apihub.v1.ApiHub.ListApiOperations]: <doc:ApiHubClient/listApiOperations(request:options:)>
    indirect case openApiSpecDetails(OpenApiSpecDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.SpecDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
