// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a spec associated with an API version in the API
/// Hub. Note that specs of various types can be uploaded, however
/// parsing of details is supported for OpenAPI spec currently.
public struct Spec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the spec.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}/specs/{spec}`
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the spec.
  /// This can contain the file name of the spec.
  public var displayName: Swift.String = Swift.String()

  /// Required. The type of spec.
  /// The value should be one of the allowed values defined for
  /// `projects/{project}/locations/{location}/attributes/system-spec-type`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API.
  ///
  /// Note, this field is mandatory if content is provided.
  public var specType: AttributeValues? = nil

  /// Optional. Input only. The contents of the uploaded spec.
  public var contents: SpecContents? = nil

  /// Output only. Details parsed from the spec.
  public var details: SpecDetails? = nil

  /// Optional. The URI of the spec source in case file is uploaded
  /// from an external version control system.
  public var sourceUri: Swift.String = Swift.String()

  /// Output only. The time at which the spec was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the spec was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The lint response for the spec.
  public var lintResponse: LintResponse? = nil

  /// Optional. The list of user defined attributes associated with the spec.
  /// The key is the attribute name. It will be of the format:
  /// `projects/{project}/locations/{location}/attributes/{attribute}`.
  /// The value is the attribute values associated with the resource.
  public var attributes: [Swift.String: AttributeValues] = [:]

  /// Optional. The documentation of the spec.
  /// For OpenAPI spec, this will be populated from `externalDocs` in OpenAPI
  /// spec.
  public var documentation: Documentation? = nil

  /// Optional. Input only. Enum specifying the parsing mode for OpenAPI
  /// Specification (OAS) parsing.
  public var parsingMode: Spec.ParsingMode = Spec.ParsingMode()

  /// Output only. The list of sources and metadata from the sources of the spec.
  public var sourceMetadata: [SourceMetadata] = []

  /// Initialize a new instance of `Spec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Spec().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specifies the parsing mode for API specifications during creation and
  /// update.
  /// - `RELAXED`: Parsing errors in the specification content do not fail the
  /// API call.
  /// - `STRICT`: Parsing errors in the specification content result in failure
  /// of the API call.
  /// If not specified, defaults to `RELAXED`.
  public enum ParsingMode: Codable, Equatable, Sendable {
    /// Defaults to `RELAXED`.
    case unspecified
    /// Parsing of the Spec on create and update is relaxed, meaning that
    /// parsing errors the spec contents will not fail the API call.
    case relaxed
    /// Parsing of the Spec on create and update is strict, meaning that
    /// parsing errors in the spec contents will fail the API call.
    case strict
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .relaxed: return 1
      case .strict: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PARSING_MODE_UNSPECIFIED"
      case .relaxed: return "RELAXED"
      case .strict: return "STRICT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ParsingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PARSING_MODE_UNSPECIFIED": self = .unspecified
      case "RELAXED": self = .relaxed
      case "STRICT": self = .strict
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ParsingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .relaxed
      case 2: self = .strict
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .relaxed: return try container.encode(1)
      case .strict: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Spec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
