// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The metadata associated with a spec of the API version.
public struct SpecMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The spec resource to be pushed to Hub's collect layer. The ID of
  /// the spec will be generated by Hub.
  public var spec: Spec? = nil

  /// Optional. The unique identifier of the spec in the system where it was
  /// originally created.
  public var originalId: Swift.String = Swift.String()

  /// Optional. Timestamp indicating when the spec was created at the source.
  public var originalCreateTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. Timestamp indicating when the spec was last updated at the
  /// source.
  public var originalUpdateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `SpecMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpecMetadata().with { $0.spec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.SpecMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
